# Generated by Django 6.0.2 on 2026-04-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_feeledgerentry_is_deleted"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="feeledgerentry",
            new_name="fee_ledger__student_d6593f_idx",
            old_name="fee_ledger_student_deleted_idx",
        ),
    ]
